info:
  title: TournamentStats
  summary: An app for League of Legends tournament organizers to visualize their tournaments
  description: "Stats"
  version: 1.0.0
license:
  name: TODO
  url: TODO
openapi: 3.1.0
server:
  url: ../api/
  description: Server relative to the website.

components:
  schemas:
    TEMPLATE:
      type: string
  parameters:
    TEMPLATE:
      name: TEMPLATE
      in: query
      description: TEMPLATE
      required: true
      schema:
        type: string
  responses:
    TEMPLATE:
      description: TEMPLATE
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TEMPLATE'
  securitySchemes:
    auth:
      type: apiKey
      in: cookie
      name: sb-127-auth-token

tags:
  - name: Tournament
    description: Creating, editing and viewing Tournaments

security:
  - auth: []

paths:
  /tournament:
    tags:
      - Tournament
    post:
      description: Creates a new tournament
      responses:
        '200':
          description: Tournament sucessfully created
      requestBody:
        description: Information about the tournament
        content:
          'application/json':
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Name of the tournament
                private:
                  type: boolean
                  description: Wether the tournament is public or private